#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# 01-static-ip.sh — Set a static local IP on Ubuntu via netplan
#
# Reads your current IP, gateway, and interface, then writes a netplan config
# that locks in those values. Your LAN address will not change on reboot.
#
# Why: the SSH reverse tunnel and Docker host.docker.internal resolution both
#      depend on a consistent IP address for this machine on your LAN.
#
# Supports: Ubuntu 18.04+ (netplan), also detects legacy ifupdown.
# Safe to re-run — it won't overwrite if the static config already exists.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

log()  { echo "[static-ip] $*"; }
warn() { echo "[static-ip] WARNING: $*" >&2; }
die()  { echo "[static-ip] FATAL: $*" >&2; exit 1; }

# ── Detect primary interface ───────────────────────────────────────────────
IFACE=$(ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1)
[[ -n "$IFACE" ]] || die "Could not detect default network interface."
log "Primary interface: $IFACE"

# ── Detect current IP, prefix, gateway ────────────────────────────────────
CURRENT_CIDR=$(ip addr show "$IFACE" | awk '/inet / {print $2}' | head -1)
[[ -n "$CURRENT_CIDR" ]] || die "No IPv4 address on $IFACE."

IP_ADDR="${CURRENT_CIDR%/*}"
PREFIX="${CURRENT_CIDR#*/}"
GATEWAY=$(ip route show default | awk '/default/ {print $3}' | head -1)
[[ -n "$GATEWAY" ]] || die "Could not detect default gateway."

log "Current IP  : $IP_ADDR/$PREFIX"
log "Gateway     : $GATEWAY"
log "Will write  : /etc/netplan/99-openclaw-static.yaml"

# ── Check if already configured ───────────────────────────────────────────
NETPLAN_FILE="/etc/netplan/99-openclaw-static.yaml"
if [[ -f "$NETPLAN_FILE" ]]; then
    log "Static IP config already exists at $NETPLAN_FILE — skipping."
    log "Delete it and re-run to reconfigure: sudo rm $NETPLAN_FILE"
    exit 0
fi

# ── Confirm ────────────────────────────────────────────────────────────────
echo ""
echo "  This will set a static IP on $IFACE:"
echo "    IP      : $IP_ADDR/$PREFIX"
echo "    Gateway : $GATEWAY"
echo "    DNS     : 1.1.1.1, 8.8.8.8"
echo ""
echo "  Your current SSH session will remain active."
echo "  The IP address will not change."
echo ""
printf "  Proceed? [y/N] "; read -r confirm
[[ "${confirm,,}" == "y" ]] || { log "Skipped."; exit 0; }

# ── Write netplan config ───────────────────────────────────────────────────
sudo tee "$NETPLAN_FILE" > /dev/null << EOF
# Generated by openclaw-docker-agent setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Static IP for OpenClaw home server — do not edit while stack is running.
network:
  version: 2
  ethernets:
    ${IFACE}:
      dhcp4: false
      addresses:
        - ${IP_ADDR}/${PREFIX}
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      # Disable DHCP-pushed routes to avoid conflicts
      dhcp4-overrides:
        route-metric: 100
EOF

sudo chmod 600 "$NETPLAN_FILE"
log "Config written to $NETPLAN_FILE"

# ── Apply ──────────────────────────────────────────────────────────────────
log "Applying netplan config (network will briefly reconnect)..."
sudo netplan apply 2>&1 | grep -v "^$" || true

# ── Verify ────────────────────────────────────────────────────────────────
sleep 2
NEW_IP=$(ip addr show "$IFACE" | awk '/inet / {print $2}' | head -1)
if [[ "$NEW_IP" == "$CURRENT_CIDR" ]]; then
    log "Static IP confirmed: $NEW_IP ✓"
else
    warn "IP after apply: $NEW_IP (expected $CURRENT_CIDR). Check netplan config if unexpected."
fi

echo ""
log "Add a DHCP reservation in your router for MAC $(ip link show "$IFACE" | awk '/ether/ {print $2}')"
log "to ensure the router never tries to assign this IP to another device."
